# Generated by Django 5.2.3 on 2025-08-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_enable_timescaledb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTMint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nft_id', models.UUIDField()),
                ('owner_user_id', models.UUIDField(null=True)),
                ('token_id', models.TextField(null=True)),
                ('tx_hash', models.TextField(null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nftopia_analytics"."nft_mints',
            },
        ),
        migrations.CreateModel(
            name='NFTSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nft_id', models.UUIDField()),
                ('buyer_user_id', models.UUIDField(null=True)),
                ('seller_user_id', models.UUIDField(null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency', models.CharField(default='STK', max_length=16)),
                ('tx_hash', models.TextField(null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nftopia_analytics"."nft_sales',
            },
        ),
        migrations.CreateModel(
            name='NFTTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nft_id', models.UUIDField()),
                ('from_user_id', models.UUIDField(null=True)),
                ('to_user_id', models.UUIDField(null=True)),
                ('tx_hash', models.TextField(null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nftopia_analytics"."nft_transfers',
            },
        ),
    ]
