# Generated by Django 5.2.3 on 2025-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('buyer_id', models.UUIDField(db_column='buyerId')),
                ('seller_id', models.UUIDField(db_column='sellerId')),
                ('nft_id', models.UUIDField(db_column='nftId')),
                ('auction_id', models.UUIDField(blank=True, db_column='auctionId', null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('transaction_hash', models.CharField(db_column='transactionHash', max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'public"."transaction',
                'managed': False,
            },
        ),
    ]
