# Generated by Django 5.2.3 on 2025-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token_id', models.CharField(db_column='tokenId', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, db_column='imageUrl', max_length=500, null=True)),
                ('ipfs_url', models.CharField(blank=True, db_column='ipfsUrl', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('currency', models.CharField(default='STK', max_length=16)),
                ('owner_id', models.UUIDField(db_column='ownerId')),
                ('collection_id', models.UUIDField(blank=True, db_column='collectionId', null=True)),
                ('category_id', models.UUIDField(blank=True, db_column='categoryId', null=True)),
                ('is_listed', models.BooleanField(db_column='isListed', default=False)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'public"."nft',
                'managed': False,
            },
        ),
    ]
